[package]
name = "raptordb"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
derive_more = { version = "2.1.1", features = ["full"] }
log = "0.4.29"
osmpbf = "0.3.8"
rayon = "1.11.0"


